### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/dra-fair-teaching#1]
hey @EstherPlomp, any thoughts on the license of this repository? we could go for CC-BY but maybe MIT would also make sense? thanks!

**Comment by EstherPlomp** [comment]
I think for this one we're focusing on the presentation so then CC-BY makes a bit more sense. If you want to share a set up of a repository it focuses more on reusing the code so then MIT would make most sense? We could add CC-BY here as the primary license and then add that the code is available under an MIT license?

**Comment by lnnrtwttkhn** [comment]
Sounds good. Let's choose CC BY for now.
