### ISSUE TITLE
Adding The Turing Way/Scriberia images to the thanks slide

### ISSUE THREAD

**Issue by EstherPlomp** [lnnrtwttkhn/dra-fair-teaching#11]
Hi @lnnrtwttkhn! 

I think it would be good to add the image credits to the thanks slide as well. I tried to add this in my version of the document but I had some interesting results for the images that you use as bullet points... 

Suggested text: 
**Images:** [Scriberia and The Turing Way](https://doi.org/10.5281/zenodo.3332807) (CC BY 4.0)

**Comment by lnnrtwttkhn** [comment]
Yes, very good point. After merging your branch (see #9), I am now doing a round of final:tm: edits on the `polishing` branch and included your suggestion in https://github.com/lnnrtwttkhn/dra-fair-teaching/commit/9e9654bc092cdcc11548ce4a7aab2bb99ea6619f.
I changed the phrasing slightly to "[Scriberia with The Turing Way community](https://doi.org/10.5281/zenodo.3332807)" to align more with their preferred way of attribution:

> When using any of the images, please include the following attribution with the specific DOI as listed on the particular Zenodo page:
>  The Turing Way Community. This illustration is created by Scriberia with The Turing Way community, used under a CC-BY 4.0 licence. DOI: [10.5281/zenodo.3332807](https://doi.org/10.5281/zenodo.3332807)
