### ISSUE TITLE
archive on zenodo

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/dra-fair-teaching#15]
hi @EstherPlomp, so we did not do this during the session, but I would still add this repo to Zenodo.
anything we should fix or take care of beforehand? thanks!

**Comment by EstherPlomp** [comment]
I think we should be all sorted right? Nothing jumps to mind for now, so I think we should just go ahead!

**Comment by lnnrtwttkhn** [comment]
we have a DOI now: https://zenodo.org/record/8296951 :tada:
