### ISSUE TITLE
how to handle static files (e.g., images)?

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/dra-fair-teaching#3]
Hi @EstherPlomp, any thoughts on how to handle static files like images in this repo?
I often keep them in a separate cloud storage and then automatically download them into the repo (but not commit them) in order to keep the repository size small. however, this is a bit more complicated and perhaps a but unnecessary here since we are likely not including many large images anyways. let me know which way you would prefer to handle static files. thanks!

**Comment by EstherPlomp** [comment]
I think it might be nicer to include them in the repo and try to avoid too many images?

I don't have a lot of experience with doing it otherwise actually - but happy to also give that a try if you were planning to put images everywhere :)

**Comment by lnnrtwttkhn** [comment]
Thanks for you feedback! I ended up including all images as weblinks for now. Not really reproducible if the URLs change, but fine for now, I think.  I would close this issue for now.
